esphome:
  name: somose
  name_add_mac_suffix: true
  includes:
  - somose.h

#
esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API 
#api:                               # uncomment if you want to use Home Assistant
#  password: "yourAPIPassword"      # uncomment if you want to use Home Assistant

ota:
  password: "yourOTAPassword"       # add an OTA password

wifi:
  ssid: "yourSSID"                  # add the SSID of your (sensor) WLAN
  password: "yourPassword"          # add the password of your (sensor) WLAN
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Moisture Sensor Fallback Hotspot"
    password: "yourAPPassword"

captive_portal:

i2c:
  sda: GPIO21                       # usually GPIO21 for ESP32 and GPIO4 for ESP8266
  scl: GPIO22                       # usually GPIO22 for ESP32 and GPIO5 for ESP8266
  frequency: 50kHz
  scan: true
  id: bus_a
    

sensor:
  - platform: custom
    id: somosesensor1
    lambda: |-
      auto somose1 = new SoMoSe(0x55);
      App.register_component(somose1);
      return {somose1->temperature_sensor, somose1->moisture_sensor};
    sensors:
      - name: "somose1_temperature"
        unit_of_measurement: °C
        accuracy_decimals: 0
      - name: "somose1_moisture"
        unit_of_measurement: '%'
        accuracy_decimals: 0
        
# if you have more then one sensor per bus, add additional sensors
#  - platform: custom
#    id: somosesensor2
#    lambda: |-
#      auto somose2 = new SoMoSe(0x56);
#      App.register_component(somose2);
#      return {somose2->temperature_sensor, somose2->moisture_sensor};
#    sensors:
#      - name: "somose2_temperature"
#        unit_of_measurement: °C
#        accuracy_decimals: 0
#      - name: "somose2_moisture"
#        unit_of_measurement: '%'
#        accuracy_decimals: 0

# enable MQTT - find more configuration variables here: https://esphome.io/components/mqtt.html
mqtt:
  broker: 192.168.0.1               # add IP to your MQTT broker
  username: "yourMQTTUsername"      # add username of your MQTT user
  password: "yourMQTTPassword"      # add password of your MQTT user

  
